# -*- mode: Ruby; tab-width: 4; -*-
source :gemcutter

gem 'bundler'
gem 'require_all'
# gem 'gosu', "0.7.20"
gem 'texplay'
gem 'chipmunk'
gem 'chingu', :git =>  "http://github.com/HakubJozak/chingu.git"



group :debug do
  gem 'awesome_print', :require => 'ap'
#  gem 'ruby-debug19', :require => 'ruby-debug'
end

group :test do
  gem 'minitest', :require => 'minitest/unit'
  gem 'minitest', :require => 'minitest/mock'
  gem 'mynyml-redgreen'
end
